<center><Bold><font size ='+2'> FRAUD DETECTION - UNDERBALANCE </Bold></center></font>


In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.under_sampling import EditedNearestNeighbours
from imblearn.under_sampling import CondensedNearestNeighbour
from imblearn.under_sampling import NeighbourhoodCleaningRule
from imblearn.under_sampling import ClusterCentroids
from imblearn.under_sampling import RandomUnderSampler
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, auc, precision_recall_curve,roc_curve, accuracy_score, cohen_kappa_score
from sklearn.preprocessing import StandardScaler
from sklearn.manifold import TSNE
from sklearn.utils import shuffle
import matplotlib.gridspec as gridspec
from sklearn import tree
import seaborn as sns
%matplotlib inline

In [94]:
df = pd.read_csv("creditcard.csv")
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...         V21       V22       V23       V24  \
0  0.098698  0.363787  ...   -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425  ...   -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  ...    0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024  ...   -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  ...   -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [0]:
# Didnt do this for underbalanced
# Based on observation of data overlap above, try out a second dataset with redunancies removed
# df= df.drop(['V28','V27','V23','V8'], axis =1)
# Later - can re run everything after running the following line
#data = clean_data

In [0]:
X = np.array(df.iloc[:, df.columns != 'Class'])
y = np.array(df.iloc[:, df.columns == 'Class'])
print('Shape of X: {}'.format(X.shape))
print('Shape of y: {}'.format(y.shape))

Shape of X: (284807, 30)
Shape of y: (284807, 1)


<center><Bold><font size ='+2'> SPLITTING DATA </Bold></center></font>

In [0]:
from sklearn.model_selection import train_test_split

#splitting data to train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

print("Number transactions X_train dataset: ", X_train.shape)
print("Number transactions y_train dataset: ", y_train.shape)
print("Number transactions X_test dataset: ", X_test.shape)
print("Number transactions y_test dataset: ", y_test.shape)

print(np.unique(y_train, return_counts=True))
np.unique(y_test, return_counts=True)





Number transactions X_train dataset:  (199364, 30)
Number transactions y_train dataset:  (199364, 1)
Number transactions X_test dataset:  (85443, 30)
Number transactions y_test dataset:  (85443, 1)
(array([0, 1]), array([199019,    345]))


(array([0, 1]), array([85296,   147]))

<center><Bold><font size ='+2'>APPLYING RANDOM & INFORMATIVE UNDERSAMPLING TECHNIQUES TO DERIVE 6 UNDERSAMPLED DATASETS</Bold></center></font>

In [0]:
# Applying Random UnderSampling (50% of Minority Class) - RUS50
print("Before UnderSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before UnderSampling, counts of label '0': {} \n".format(sum(y_train==0)))

rus = RandomUnderSampler(sampling_strategy=1,random_state=5)
X_train_rus50, y_train_rus50 = rus.fit_sample(X_train, y_train.ravel())

print('After UnderSampling, the shape of train_X: {}'.format(X_train_rus50.shape))
print('After UnderSampling, the shape of train_y: {} \n'.format(y_train_rus50.shape))

print("After UnderSampling, counts of label '1': {}".format(sum(y_train_rus50==1)))
print("After UnderSampling, counts of label '0': {}".format(sum(y_train_rus50==0)))                                                                   

Before UnderSampling, counts of label '1': [345]
Before UnderSampling, counts of label '0': [199019] 

After UnderSampling, the shape of train_X: (690, 30)
After UnderSampling, the shape of train_y: (690,) 

After UnderSampling, counts of label '1': 345
After UnderSampling, counts of label '0': 345


In [0]:
# Applying Random UnderSampling (10% of Minority Class) - RUS10
print("Before UnderSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before UnderSampling, counts of label '0': {} \n".format(sum(y_train==0)))

rus = RandomUnderSampler(sampling_strategy=0.10, random_state=100)
X_train_rus10, y_train_rus10 = rus.fit_sample(X_train, y_train.ravel())

print('After UnderSampling, the shape of train_X: {}'.format(X_train_rus10.shape))
print('After UnderSampling, the shape of train_y: {} \n'.format(y_train_rus10.shape))

print("After UnderSampling, counts of label '1': {}".format(sum(y_train_rus10==1)))
print("After UnderSampling, counts of label '0': {}".format(sum(y_train_rus10==0)))

Before UnderSampling, counts of label '1': [345]
Before UnderSampling, counts of label '0': [199019] 

After UnderSampling, the shape of train_X: (3795, 30)
After UnderSampling, the shape of train_y: (3795,) 

After UnderSampling, counts of label '1': 345
After UnderSampling, counts of label '0': 3450


In [0]:
# Applying Random UnderSampling (1% of Minority Class) - RUS1
print("Before UnderSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before UnderSampling, counts of label '0': {} \n".format(sum(y_train==0)))

rus = RandomUnderSampler(sampling_strategy=0.01, random_state=100)
X_train_rus1, y_train_rus1 = rus.fit_sample(X_train, y_train.ravel())

print('After UnderSampling, the shape of train_X: {}'.format(X_train_rus10.shape))
print('After UnderSampling, the shape of train_y: {} \n'.format(y_train_rus1.shape))

print("After UnderSampling, counts of label '1': {}".format(sum(y_train_rus1==1)))
print("After UnderSampling, counts of label '0': {}".format(sum(y_train_rus1==0)))

Before UnderSampling, counts of label '1': [345]
Before UnderSampling, counts of label '0': [199019] 

After UnderSampling, the shape of train_X: (3795, 30)
After UnderSampling, the shape of train_y: (34845,) 

After UnderSampling, counts of label '1': 345
After UnderSampling, counts of label '0': 34500


In [0]:
# Applying Informative UnderSampling (Edited Nearest Neighbours) - ENN
print("Before UnderSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before UnderSampling, counts of label '0': {} \n".format(sum(y_train==0)))

enn = EditedNearestNeighbours(sampling_strategy='auto')
X_train_enn, y_train_enn = enn.fit_sample(X_train, y_train.ravel())

print('After UnderSampling, the shape of train_X: {}'.format(X_train_enn.shape))
print('After UnderSampling, the shape of train_y: {} \n'.format(y_train_enn.shape))

print("After UnderSampling, counts of label '1': {}".format(sum(y_train_enn==1)))
print("After UnderSampling, counts of label '0': {}".format(sum(y_train_enn==0)))

Before UnderSampling, counts of label '1': [345]
Before UnderSampling, counts of label '0': [199019] 

After UnderSampling, the shape of train_X: (199031, 30)
After UnderSampling, the shape of train_y: (199031,) 

After UnderSampling, counts of label '1': 345
After UnderSampling, counts of label '0': 198686


In [0]:
# Applying Informative UnderSampling (Condensed Nearest Neighbour) - CNN
print("Before UnderSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before UnderSampling, counts of label '0': {} \n".format(sum(y_train==0)))

cnn = CondensedNearestNeighbour(sampling_strategy='auto', random_state = 17)
X_train_cnn, y_train_cnn = cnn.fit_sample(X_train, y_train.ravel())

print('After UnderSampling, the shape of train_X: {}'.format(X_train_cnn.shape))
print('After UnderSampling, the shape of train_y: {} \n'.format(y_train_cnn.shape))

print("After UnderSampling, counts of label '1': {}".format(sum(y_train_cnn==1)))
print("After UnderSampling, counts of label '0': {}".format(sum(y_train_cnn==0)))

Before UnderSampling, counts of label '1': [345]
Before UnderSampling, counts of label '0': [199019] 

After UnderSampling, the shape of train_X: (2142, 30)
After UnderSampling, the shape of train_y: (2142,) 

After UnderSampling, counts of label '1': 345
After UnderSampling, counts of label '0': 1797


In [0]:
# Applying Informative UnderSampling (Neighbourhood Cleaning Rule) - NCL
print("Before UnderSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before UnderSampling, counts of label '0': {} \n".format(sum(y_train==0)))

ncl = NeighbourhoodCleaningRule(sampling_strategy='auto')
X_train_ncl, y_train_ncl = ncl.fit_sample(X_train, y_train.ravel())

print('After UnderSampling, the shape of train_X: {}'.format(X_train_ncl.shape))
print('After UnderSampling, the shape of train_y: {} \n'.format(y_train_ncl.shape))

print("After UnderSampling, counts of label '1': {}".format(sum(y_train_ncl==1)))
print("After UnderSampling, counts of label '0': {}".format(sum(y_train_ncl==0)))

Before UnderSampling, counts of label '1': [345]
Before UnderSampling, counts of label '0': [199019] 

After UnderSampling, the shape of train_X: (198486, 30)
After UnderSampling, the shape of train_y: (198486,) 

After UnderSampling, counts of label '1': 345
After UnderSampling, counts of label '0': 198141


<center><Bold><font size ='+2'>SVM FOR UNDERBALANCED DATASETS</Bold></center></font>

In [0]:
lsvm = svm.LinearSVC(C=1.0, dual=False)
sv=lsvm.fit(X_train_rus50, y_train_rus50.ravel())
y_pred_rus50_svm = lsvm.predict(X_test)
print (sv)

print('Confusion Matrix for SVM on RUS50 Dataset')
print(confusion_matrix(y_test, y_pred_rus50_svm))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus50_svm))
print(classification_report(y_test, y_pred_rus50_svm))
# plot_confusion_matrix(y_test, y_pred)
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus50_svm))

LinearSVC(C=1.0, class_weight=None, dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)
Confusion Matrix for SVM on RUS50 Dataset
[[82718  2578]
 [   13   134]]
Accuracy: 0.9696756902262327
              precision    recall  f1-score   support

           0       1.00      0.97      0.98     85296
           1       0.05      0.91      0.09       147

   micro avg       0.97      0.97      0.97     85443
   macro avg       0.52      0.94      0.54     85443
weighted avg       1.00      0.97      0.98     85443

Kappa Score: 0.09077137318584805


In [0]:
lsvm = svm.LinearSVC(C=1.0, dual=False)
sv=lsvm.fit(X_train_rus10, y_train_rus10.ravel())
y_pred_rus10_svm = lsvm.predict(X_test)
print (sv)

print('Confusion Matrix for SVM on RUS10 Dataset')
print(confusion_matrix(y_test, y_pred_rus10_svm))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus10_svm))
print(classification_report(y_test, y_pred_rus10_svm))
# plot_confusion_matrix(y_test, y_pred)
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus10_svm))

LinearSVC(C=1.0, class_weight=None, dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)
Confusion Matrix for SVM on RUS10 Dataset
[[85078   218]
 [   40   107]]
Accuracy: 0.9969804431024192
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.33      0.73      0.45       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.66      0.86      0.73     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.4520916948260042


In [0]:
lsvm = svm.LinearSVC(C=1.0, dual=False)
sv=lsvm.fit(X_train_rus1, y_train_rus1.ravel())
y_pred_rus1_svm = lsvm.predict(X_test)
print (sv)

print('Confusion Matrix for SVM on RUS1 Dataset')
print(confusion_matrix(y_test, y_pred_rus1_svm))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus1_svm))
print(classification_report(y_test, y_pred_rus1_svm))
# plot_confusion_matrix(y_test, y_pred)
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus1_svm))

LinearSVC(C=1.0, class_weight=None, dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)
Confusion Matrix for SVM on RUS1 Dataset
[[85163   133]
 [   40   107]]
Accuracy: 0.9979752583593741
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.45      0.73      0.55       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.72      0.86      0.78     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.5520156288598568


In [0]:
lsvm = svm.LinearSVC(C=1.0, dual=False)
sv=lsvm.fit(X_train_enn, y_train_enn.ravel())
y_pred_enn_svm = lsvm.predict(X_test)
print (sv)

print('Confusion Matrix for SVM on ENN Dataset')
print(confusion_matrix(y_test, y_pred_enn_svm))  
print ('Accuracy:', accuracy_score(y_test, y_pred_enn_svm))
print(classification_report(y_test, y_pred_enn_svm))
# plot_confusion_matrix(y_test, y_pred)
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_enn_svm))

LinearSVC(C=1.0, class_weight=None, dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)
Confusion Matrix for SVM on ENN Dataset
[[85283    13]
 [   75    72]]
Accuracy: 0.9989700736163291
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.85      0.49      0.62       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.92      0.74      0.81     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.6202108660028955


In [0]:
lsvm = svm.LinearSVC(C=1.0, dual=False)
sv=lsvm.fit(X_train_cnn, y_train_cnn.ravel())
y_pred_cnn_svm = lsvm.predict(X_test)
print (sv)

print('Confusion Matrix for SVM on CNN Dataset')
print(confusion_matrix(y_test, y_pred_cnn_svm))  
print ('Accuracy:', accuracy_score(y_test, y_pred_cnn_svm))
print(classification_report(y_test, y_pred_cnn_svm))
# plot_confusion_matrix(y_test, y_pred)
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_cnn_svm))

LinearSVC(C=1.0, class_weight=None, dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)
Confusion Matrix for SVM on CNN Dataset
[[85086   210]
 [   38   109]]
Accuracy: 0.9970974801914727
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.34      0.74      0.47       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.67      0.87      0.73     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.4665546499765423


In [0]:
lsvm = svm.LinearSVC(C=1.0, dual=False)
sv=lsvm.fit(X_train_ncl, y_train_ncl.ravel())
y_pred_ncl_svm = lsvm.predict(X_test)
print (sv)

print('Confusion Matrix for SVM on NCL Dataset')
print(confusion_matrix(y_test, y_pred_ncl_svm))  
print ('Accuracy:', accuracy_score(y_test, y_pred_ncl_svm))
print(classification_report(y_test, y_pred_ncl_svm))
# plot_confusion_matrix(y_test, y_pred)
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_ncl_svm))

LinearSVC(C=1.0, class_weight=None, dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)
Confusion Matrix for SVM on NCL Dataset
[[85285    11]
 [   55    92]]
Accuracy: 0.9992275552122467
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.89      0.63      0.74       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.95      0.81      0.87     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.7356252099110061


<center><Bold><font size ='+2'>NAIVE BAYES FOR UNDERBALANCED DATASETS</Bold></center></font>

In [0]:
classifier = GaussianNB()
model=classifier.fit(X_train_rus50, y_train_rus50.ravel())
y_pred_rus50_nb = model.predict(X_test)
print (model)

print('Confusion Matrix for Naive Bayes on RUS50 Dataset')
print(confusion_matrix(y_test, y_pred_rus50_nb))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus50_nb))
print(classification_report(y_test, y_pred_rus50_nb))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus50_nb))

GaussianNB(priors=None, var_smoothing=1e-09)
Confusion Matrix for Naive Bayes on RUS50 Dataset
[[84007  1289]
 [   43   104]]
Accuracy: 0.984410659738071
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     85296
           1       0.07      0.71      0.14       147

   micro avg       0.98      0.98      0.98     85443
   macro avg       0.54      0.85      0.56     85443
weighted avg       1.00      0.98      0.99     85443

Kappa Score: 0.13236446998512907


In [0]:
classifier = GaussianNB()
model=classifier.fit(X_train_rus10, y_train_rus10.ravel())
y_pred_rus10_nb = model.predict(X_test)
print (model)

print('Confusion Matrix for Naive Bayes on RUS10 Dataset')
print(confusion_matrix(y_test, y_pred_rus10_nb))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus10_nb))
print(classification_report(y_test, y_pred_rus10_nb))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus10_nb))

GaussianNB(priors=None, var_smoothing=1e-09)
Confusion Matrix for Naive Bayes on RUS10 Dataset
[[84696   600]
 [   48    99]]
Accuracy: 0.9924159966293319
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     85296
           1       0.14      0.67      0.23       147

   micro avg       0.99      0.99      0.99     85443
   macro avg       0.57      0.83      0.62     85443
weighted avg       1.00      0.99      0.99     85443

Kappa Score: 0.2318587235453765


In [0]:
classifier = GaussianNB()
model=classifier.fit(X_train_rus1, y_train_rus1.ravel())
y_pred_rus1_nb = model.predict(X_test)
print (model)

print('Confusion Matrix for Naive Bayes on RUS1 Dataset')
print(confusion_matrix(y_test, y_pred_rus1_nb))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus1_nb))
print(classification_report(y_test, y_pred_rus1_nb))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus1_nb))

GaussianNB(priors=None, var_smoothing=1e-09)
Confusion Matrix for Naive Bayes on RUS1 Dataset
[[84703   593]
 [   49    98]]
Accuracy: 0.9924862188827639
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     85296
           1       0.14      0.67      0.23       147

   micro avg       0.99      0.99      0.99     85443
   macro avg       0.57      0.83      0.62     85443
weighted avg       1.00      0.99      0.99     85443

Kappa Score: 0.23171034851357342


In [0]:
classifier = GaussianNB()
model=classifier.fit(X_train_enn, y_train_enn.ravel())
y_pred_enn_nb = model.predict(X_test)
print (model)

print('Confusion Matrix for Naive Bayes on ENN Dataset')
print(confusion_matrix(y_test, y_pred_enn_nb))  
print ('Accuracy:', accuracy_score(y_test, y_pred_enn_nb))
print(classification_report(y_test, y_pred_enn_nb))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_enn_nb))

GaussianNB(priors=None, var_smoothing=1e-09)
Confusion Matrix for Naive Bayes on ENN Dataset
[[84749   547]
 [   52    95]]
Accuracy: 0.9929894783656941
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     85296
           1       0.15      0.65      0.24       147

   micro avg       0.99      0.99      0.99     85443
   macro avg       0.57      0.82      0.62     85443
weighted avg       1.00      0.99      1.00     85443

Kappa Score: 0.23867959938403982


In [0]:
classifier = GaussianNB()
model=classifier.fit(X_train_cnn, y_train_cnn.ravel())
y_pred_cnn_nb = model.predict(X_test)
print (model)

print('Confusion Matrix for Naive Bayes on CNN Dataset')
print(confusion_matrix(y_test, y_pred_cnn_nb))  
print ('Accuracy:', accuracy_score(y_test, y_pred_cnn_nb))
print(classification_report(y_test, y_pred_cnn_nb))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_cnn_nb))

GaussianNB(priors=None, var_smoothing=1e-09)
Confusion Matrix for Naive Bayes on CNN Dataset
[[84797   499]
 [   48    99]]
Accuracy: 0.9935980712287724
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     85296
           1       0.17      0.67      0.27       147

   micro avg       0.99      0.99      0.99     85443
   macro avg       0.58      0.83      0.63     85443
weighted avg       1.00      0.99      1.00     85443

Kappa Score: 0.263738294339236


In [0]:
classifier = GaussianNB()
model=classifier.fit(X_train_ncl, y_train_ncl.ravel())
y_pred_ncl_nb = model.predict(X_test)
print (model)

print('Confusion Matrix for Naive Bayes on NCL Dataset')
print(confusion_matrix(y_test, y_pred_ncl_nb))  
print ('Accuracy:', accuracy_score(y_test, y_pred_ncl_nb))
print(classification_report(y_test, y_pred_ncl_nb))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_ncl_nb))

GaussianNB(priors=None, var_smoothing=1e-09)
Confusion Matrix for Naive Bayes on NCL Dataset
[[84750   546]
 [   52    95]]
Accuracy: 0.9930011820745994
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     85296
           1       0.15      0.65      0.24       147

   micro avg       0.99      0.99      0.99     85443
   macro avg       0.57      0.82      0.62     85443
weighted avg       1.00      0.99      1.00     85443

Kappa Score: 0.23898667617506708


<center><Bold><font size ='+2'>RANDOM FOREST FOR UNDERBALANCED DATASETS</Bold></center></font>

In [0]:
rf = RandomForestClassifier(n_estimators=10, n_jobs=4)
rfmod=rf.fit(X_train_rus50, y_train_rus50.ravel())
y_pred_rus50_rf = rf.predict(X_test)
print (rfmod)

print('Confusion Matrix for Random Forest on RUS50 Dataset')
print(confusion_matrix(y_test, y_pred_rus50_rf))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus50_rf))
print(classification_report(y_test, y_pred_rus50_rf))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus50_rf))

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=4,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
Confusion Matrix for Random Forest on RUS50 Dataset
[[83272  2024]
 [   16   131]]
Accuracy: 0.9761244338330817
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     85296
           1       0.06      0.89      0.11       147

   micro avg       0.98      0.98      0.98     85443
   macro avg       0.53      0.93      0.55     85443
weighted avg       1.00      0.98      0.99     85443

Kappa Score: 0.11095030009147977


In [0]:
rf = RandomForestClassifier(n_estimators=10, n_jobs=4)
rfmod=rf.fit(X_train_rus10, y_train_rus10.ravel())
y_pred_rus10_rf = rf.predict(X_test)
print (rfmod)

print('Confusion Matrix for Random Forest on RUS10 Dataset')
print(confusion_matrix(y_test, y_pred_rus10_rf))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus10_rf))
print(classification_report(y_test, y_pred_rus10_rf))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus10_rf))

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=4,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
Confusion Matrix for Random Forest on RUS10 Dataset
[[85216    80]
 [   22   125]]
Accuracy: 0.9988062216916541
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.61      0.85      0.71       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.80      0.92      0.85     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.7096454231600258


In [0]:
rf = RandomForestClassifier(n_estimators=10, n_jobs=4)
rfmod=rf.fit(X_train_rus1, y_train_rus1.ravel())
y_pred_rus1_rf = rf.predict(X_test)
print (rfmod)

print('Confusion Matrix for Random Forest on RUS1 Dataset')
print(confusion_matrix(y_test, y_pred_rus1_rf))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus1_rf))
print(classification_report(y_test, y_pred_rus1_rf))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus1_rf))

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=4,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
Confusion Matrix for Random Forest on RUS1 Dataset
[[85269    27]
 [   26   121]]
Accuracy: 0.9993797034280163
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.82      0.82      0.82       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.91      0.91      0.91     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.8200283020071438


In [0]:
rf = RandomForestClassifier(n_estimators=10, n_jobs=4)
rfmod=rf.fit(X_train_enn, y_train_enn.ravel())
y_pred_enn_rf = rf.predict(X_test)
print (rfmod)

print('Confusion Matrix for Random Forest on ENN Dataset')
print(confusion_matrix(y_test, y_pred_enn_rf))  
print ('Accuracy:', accuracy_score(y_test, y_pred_enn_rf))
print(classification_report(y_test, y_pred_enn_rf))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_enn_rf))

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=4,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
Confusion Matrix for Random Forest on ENN Dataset
[[85290     6]
 [   35   112]]
Accuracy: 0.9995201479348805
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.95      0.76      0.85       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.97      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.8450456023772075


In [0]:
rf = RandomForestClassifier(n_estimators=10, n_jobs=4)
rfmod=rf.fit(X_train_cnn, y_train_cnn.ravel())
y_pred_cnn_rf = rf.predict(X_test)
print (rfmod)

print('Confusion Matrix for Random Forest on CNN Dataset')
print(confusion_matrix(y_test, y_pred_cnn_rf))  
print ('Accuracy:', accuracy_score(y_test, y_pred_cnn_rf))
print(classification_report(y_test, y_pred_cnn_rf))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_cnn_rf))

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=4,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
Confusion Matrix for Random Forest on CNN Dataset
[[85183   113]
 [   24   123]]
Accuracy: 0.9983965918799668
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.52      0.84      0.64       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.76      0.92      0.82     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.6415376255328962


In [0]:
rf = RandomForestClassifier(n_estimators=10, n_jobs=4)
rfmod=rf.fit(X_train_ncl, y_train_ncl.ravel())
y_pred_ncl_rf = rf.predict(X_test)
print (rfmod)

print('Confusion Matrix for Random Forest on NCL Dataset')
print(confusion_matrix(y_test, y_pred_ncl_rf))  
print ('Accuracy:', accuracy_score(y_test, y_pred_ncl_rf))
print(classification_report(y_test, y_pred_ncl_rf))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_ncl_rf))

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=4,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
Confusion Matrix for Random Forest on NCL Dataset
[[85291     5]
 [   39   108]]
Accuracy: 0.9994850368081645
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.96      0.73      0.83       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.98      0.87      0.92     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.8305157732243474


<center><Bold><font size ='+2'>DECISION TREE FOR UNDERBALANCED DATASETS</Bold></center></font>

In [0]:
decisionTreeClf = tree.DecisionTreeClassifier()
decisionTreeClf = decisionTreeClf.fit(X_train_rus50, y_train_rus50.ravel())
y_pred_rus50_dt = decisionTreeClf.predict(X_test)
decisionTreeClf

print('Confusion Matrix for Decision Tree on RUS50 Dataset')
print(confusion_matrix(y_test, y_pred_rus50_dt))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus50_dt))
print(classification_report(y_test, y_pred_rus50_dt))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus50_dt))

Confusion Matrix for Decision Tree on RUS50 Dataset
[[79534  5762]
 [   21   126]]
Accuracy: 0.9323174514003487
              precision    recall  f1-score   support

           0       1.00      0.93      0.96     85296
           1       0.02      0.86      0.04       147

   micro avg       0.93      0.93      0.93     85443
   macro avg       0.51      0.89      0.50     85443
weighted avg       1.00      0.93      0.96     85443

Kappa Score: 0.038528687155860664


In [0]:
decisionTreeClf = tree.DecisionTreeClassifier()
decisionTreeClf = decisionTreeClf.fit(X_train_rus10, y_train_rus10.ravel())
y_pred_rus10_dt = decisionTreeClf.predict(X_test)
decisionTreeClf

print('Confusion Matrix for Decision Tree on RUS10 Dataset')
print(confusion_matrix(y_test, y_pred_rus10_dt))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus10_dt))
print(classification_report(y_test, y_pred_rus10_dt))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus10_dt))

Confusion Matrix for Decision Tree on RUS10 Dataset
[[83840  1456]
 [   21   126]]
Accuracy: 0.9827136219467949
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     85296
           1       0.08      0.86      0.15       147

   micro avg       0.98      0.98      0.98     85443
   macro avg       0.54      0.92      0.57     85443
weighted avg       1.00      0.98      0.99     85443

Kappa Score: 0.14305101673986997


In [0]:
decisionTreeClf = tree.DecisionTreeClassifier()
decisionTreeClf = decisionTreeClf.fit(X_train_rus1, y_train_rus1.ravel())
y_pred_rus1_dt = decisionTreeClf.predict(X_test)
decisionTreeClf

print('Confusion Matrix for Decision Tree on RUS1 Dataset')
print(confusion_matrix(y_test, y_pred_rus1_dt))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus1_dt))
print(classification_report(y_test, y_pred_rus1_dt))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus1_dt))

Confusion Matrix for Decision Tree on RUS1 Dataset
[[85147   149]
 [   28   119]]
Accuracy: 0.9979284435237527
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.44      0.81      0.57       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.72      0.90      0.79     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.5725441394901246


In [0]:
decisionTreeClf = tree.DecisionTreeClassifier()
decisionTreeClf = decisionTreeClf.fit(X_train_enn, y_train_enn.ravel())
y_pred_enn_dt = decisionTreeClf.predict(X_test)
decisionTreeClf

print('Confusion Matrix for Decision Tree on ENN Dataset')
print(confusion_matrix(y_test, y_pred_enn_dt))  
print ('Accuracy:', accuracy_score(y_test, y_pred_enn_dt))
print(classification_report(y_test, y_pred_enn_dt))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_enn_dt))

Confusion Matrix for Decision Tree on ENN Dataset
[[85265    31]
 [   38   109]]
Accuracy: 0.9991924440855307
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.78      0.74      0.76       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.89      0.87      0.88     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.7591776653067948


In [0]:
decisionTreeClf = tree.DecisionTreeClassifier()
decisionTreeClf = decisionTreeClf.fit(X_train_cnn, y_train_cnn.ravel())
y_pred_cnn_dt = decisionTreeClf.predict(X_test)
decisionTreeClf

print('Confusion Matrix for Decision Tree on CNN Dataset')
print(confusion_matrix(y_test, y_pred_cnn_dt))  
print ('Accuracy:', accuracy_score(y_test, y_pred_cnn_dt))
print(classification_report(y_test, y_pred_cnn_dt))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_cnn_dt))

Confusion Matrix for Decision Tree on CNN Dataset
[[83216  2080]
 [   22   125]]
Accuracy: 0.9753988038809499
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     85296
           1       0.06      0.85      0.11       147

   micro avg       0.98      0.98      0.98     85443
   macro avg       0.53      0.91      0.55     85443
weighted avg       1.00      0.98      0.99     85443

Kappa Score: 0.10340023431052381


In [75]:
decisionTreeClf = tree.DecisionTreeClassifier()
decisionTreeClf = decisionTreeClf.fit(X_train_ncl, y_train_ncl.ravel())
y_pred_ncl_dt = rf.predict(X_test)
decisionTreeClf

print('Confusion Matrix for Decision Tree on NCL Dataset')
print(confusion_matrix(y_test, y_pred_ncl_dt))  
print ('Accuracy:', accuracy_score(y_test, y_pred_ncl_dt))
print(classification_report(y_test, y_pred_ncl_dt))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_ncl_dt))

Confusion Matrix for Decision Tree on NCL Dataset
[[85291     5]
 [   39   108]]
Accuracy: 0.9994850368081645
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.96      0.73      0.83       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.98      0.87      0.92     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.8305157732243474


<center><Bold><font size ='+2'>NEURAL NETWORK (MLP) FOR UNDERBALANCED DATASETS</Bold></center></font>

In [76]:
mlp = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(8,7), max_iter=8)  
mlp.fit(X_train_rus50, y_train_rus50.ravel())  
y_pred_rus50_mlp = mlp.predict(X_test)
mlp

print('Confusion Matrix for Neural Networks on RUS50 Dataset')
print(confusion_matrix(y_test, y_pred_rus50_mlp))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus50_mlp))
print(classification_report(y_test, y_pred_rus50_mlp))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus50_mlp))

Confusion Matrix for Neural Networks on RUS50 Dataset
[[85296     0]
 [  147     0]]
Accuracy: 0.9982795547909132
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.00      0.00      0.00       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.50      0.50      0.50     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.0


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [77]:
mlp = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(8,7), max_iter=8)  
mlp.fit(X_train_rus10, y_train_rus10.ravel())  
y_pred_rus10_mlp = mlp.predict(X_test)
mlp

print('Confusion Matrix for Neural Networks on RUS10 Dataset')
print(confusion_matrix(y_test, y_pred_rus10_mlp))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus10_mlp))
print(classification_report(y_test, y_pred_rus10_mlp))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus10_mlp))

Confusion Matrix for Neural Networks on RUS10 Dataset
[[85296     0]
 [  147     0]]
Accuracy: 0.9982795547909132
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.00      0.00      0.00       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.50      0.50      0.50     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.0


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [78]:
mlp = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(8,7), max_iter=8)  
mlp.fit(X_train_rus1, y_train_rus1.ravel())  
y_pred_rus1_mlp = mlp.predict(X_test)
mlp

print('Confusion Matrix for Neural Networks on RUS1 Dataset')
print(confusion_matrix(y_test, y_pred_rus1_mlp))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus1_mlp))
print(classification_report(y_test, y_pred_rus1_mlp))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus1_mlp))

Confusion Matrix for Neural Networks on RUS1 Dataset
[[85296     0]
 [  147     0]]
Accuracy: 0.9982795547909132
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.00      0.00      0.00       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.50      0.50      0.50     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.0


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [79]:
mlp = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(8,7), max_iter=8)  
mlp.fit(X_train_enn, y_train_enn.ravel())  
y_pred_enn_mlp = mlp.predict(X_test)
mlp

print('Confusion Matrix for Neural Networks on ENN Dataset')
print(confusion_matrix(y_test, y_pred_enn_mlp))  
print ('Accuracy:', accuracy_score(y_test, y_pred_enn_mlp))
print(classification_report(y_test, y_pred_enn_mlp))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_enn_mlp))

Confusion Matrix for Neural Networks on ENN Dataset
[[84678   618]
 [  145     2]]
Accuracy: 0.9910700701052163
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     85296
           1       0.00      0.01      0.01       147

   micro avg       0.99      0.99      0.99     85443
   macro avg       0.50      0.50      0.50     85443
weighted avg       1.00      0.99      0.99     85443

Kappa Score: 0.0024404880847637145


In [80]:
mlp = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(8,7), max_iter=8)  
mlp.fit(X_train_cnn, y_train_cnn.ravel())  
y_pred_cnn_mlp = mlp.predict(X_test)
mlp

print('Confusion Matrix for Neural Networks on CNN Dataset')
print(confusion_matrix(y_test, y_pred_cnn_mlp))  
print ('Accuracy:', accuracy_score(y_test, y_pred_cnn_mlp))
print(classification_report(y_test, y_pred_cnn_mlp))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_cnn_mlp))

Confusion Matrix for Neural Networks on CNN Dataset
[[85296     0]
 [  147     0]]
Accuracy: 0.9982795547909132
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.00      0.00      0.00       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.50      0.50      0.50     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.0


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [81]:
mlp = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(8,7), max_iter=8)  
mlp.fit(X_train_ncl, y_train_ncl.ravel())  
y_pred_ncl_mlp = mlp.predict(X_test)
mlp

print('Confusion Matrix for Neural Networks on NCL Dataset')
print(confusion_matrix(y_test, y_pred_ncl_mlp))  
print ('Accuracy:', accuracy_score(y_test, y_pred_ncl_mlp))
print(classification_report(y_test, y_pred_ncl_mlp))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_ncl_mlp))

Confusion Matrix for Neural Networks on NCL Dataset
[[85296     0]
 [  147     0]]
Accuracy: 0.9982795547909132
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.00      0.00      0.00       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.50      0.50      0.50     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.0


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


<center><Bold><font size ='+2'>LOGISTIC REGRESSION FOR UNDERBALANCED DATASETS</Bold></center></font>

In [82]:
clf = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr').fit(X_train_rus50, y_train_rus50)
y_pred_rus50_lr = clf.predict(X_test)
print(clf)

print('Confusion Matrix for Linear Regression on RUS50')
print(confusion_matrix(y_test, y_pred_rus50_lr))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus50_lr))
print(classification_report(y_test, y_pred_rus50_lr))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus50_lr))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          n_jobs=None, penalty='l2', random_state=0, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)
Confusion Matrix for Linear Regression on RUS50
[[81058  4238]
 [   18   129]]
Accuracy: 0.9501890148988215
              precision    recall  f1-score   support

           0       1.00      0.95      0.97     85296
           1       0.03      0.88      0.06       147

   micro avg       0.95      0.95      0.95     85443
   macro avg       0.51      0.91      0.52     85443
weighted avg       1.00      0.95      0.97     85443

Kappa Score: 0.05400645823755579


In [83]:
clf = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr').fit(X_train_rus10, y_train_rus10)
y_pred_rus10_lr = clf.predict(X_test)
print(clf)

print('Confusion Matrix for Linear Regression on RUS10')
print(confusion_matrix(y_test, y_pred_rus10_lr))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus10_lr))
print(classification_report(y_test, y_pred_rus10_lr))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus10_lr))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          n_jobs=None, penalty='l2', random_state=0, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)
Confusion Matrix for Linear Regression on RUS10
[[84604   692]
 [   21   126]]
Accuracy: 0.991655255550484
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     85296
           1       0.15      0.86      0.26       147

   micro avg       0.99      0.99      0.99     85443
   macro avg       0.58      0.92      0.63     85443
weighted avg       1.00      0.99      0.99     85443

Kappa Score: 0.25897853382796177


In [84]:
clf = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr').fit(X_train_rus1, y_train_rus1)
y_pred_rus1_lr = clf.predict(X_test)
print(clf)

print('Confusion Matrix for Linear Regression on RUS1')
print(confusion_matrix(y_test, y_pred_rus1_lr))  
print ('Accuracy:', accuracy_score(y_test, y_pred_rus1_lr))
print(classification_report(y_test, y_pred_rus1_lr))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_rus1_lr))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          n_jobs=None, penalty='l2', random_state=0, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)
Confusion Matrix for Linear Regression on RUS1
[[85175   121]
 [   28   119]]
Accuracy: 0.9982561473731025
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.50      0.81      0.61       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.75      0.90      0.81     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.6141637497116685


In [87]:
clf = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr').fit(X_train_enn, y_train_enn)
y_pred_enn_lr = clf.predict(X_test)
print(clf)

print('Confusion Matrix for Linear Regression on ENN')
print(confusion_matrix(y_test, y_pred_enn_lr))  
print ('Accuracy:', accuracy_score(y_test, y_pred_enn_lr))
print(classification_report(y_test, y_pred_enn_lr))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_enn_lr))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          n_jobs=None, penalty='l2', random_state=0, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)
Confusion Matrix for Linear Regression on ENN
[[85262    34]
 [   52    95]]
Accuracy: 0.9989934810341398
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.74      0.65      0.69       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.87      0.82      0.84     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.6879038709172676


In [86]:
clf = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr').fit(X_train_cnn, y_train_cnn)
y_pred_cnn_lr = clf.predict(X_test)
print(clf)

print('Confusion Matrix for Linear Regression on CNN')
print(confusion_matrix(y_test, y_pred_cnn_lr))  
print ('Accuracy:', accuracy_score(y_test, y_pred_cnn_lr))
print(classification_report(y_test, y_pred_cnn_lr))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_cnn_lr))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          n_jobs=None, penalty='l2', random_state=0, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)
Confusion Matrix for Linear Regression on CNN
[[84444   852]
 [   23   124]]
Accuracy: 0.9897592547078169
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     85296
           1       0.13      0.84      0.22       147

   micro avg       0.99      0.99      0.99     85443
   macro avg       0.56      0.92      0.61     85443
weighted avg       1.00      0.99      0.99     85443

Kappa Score: 0.21849998345799426


In [85]:
clf = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr').fit(X_train_ncl, y_train_ncl)
y_pred_ncl_lr = clf.predict(X_test)
print(clf)

print('Confusion Matrix for Linear Regression on NCL')
print(confusion_matrix(y_test, y_pred_ncl_lr))  
print ('Accuracy:', accuracy_score(y_test, y_pred_ncl_lr))
print(classification_report(y_test, y_pred_ncl_lr))
print ('Kappa Score:', cohen_kappa_score(y_test, y_pred_ncl_lr))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          n_jobs=None, penalty='l2', random_state=0, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)
Confusion Matrix for Linear Regression on NCL
[[85262    34]
 [   49    98]]
Accuracy: 0.9990285921608558
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.74      0.67      0.70       147

   micro avg       1.00      1.00      1.00     85443
   macro avg       0.87      0.83      0.85     85443
weighted avg       1.00      1.00      1.00     85443

Kappa Score: 0.7020238708838973
